/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import Carvapp.Conexion;
import Carvapp.Usuarios;
import Carvapp.Visitantes;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
/**
/**
 *
 * @author Usuario
 */
public class RegistroVisitas extends javax.swing.JFrame {

 
    /**
     * Creates new form RegistroVisitas
     */
    public RegistroVisitas() {
        initComponents();
        this.setLocationRelativeTo(null);
            VisitanteIDReg.setEnabled(false);
            NombreReg.setEnabled(false);
            Documento.setEnabled(false);
            RegistroID.setEnabled(false);
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/iconopeque.png")));

            Visitantes objetoVisitantes = new Visitantes();
            objetoVisitantes.mostrarRegistros(TablaRegistroVisitantes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraIz = new javax.swing.JPanel();
        Registrotxt = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        nombreag = new javax.swing.JLabel();
        NombreReg = new javax.swing.JTextField();
        Documentotitle = new javax.swing.JLabel();
        Documento = new javax.swing.JTextField();
        mostrarVisitantes = new javax.swing.JScrollPane();
        TablaRegistroVisitantes = new javax.swing.JTable();
        barraDer = new javax.swing.JPanel();
        IDtitle = new javax.swing.JLabel();
        VisitanteIDReg = new javax.swing.JTextField();
        BotonSalida = new javax.swing.JButton();
        BotonEntrada = new javax.swing.JButton();
        IDtitle1 = new javax.swing.JLabel();
        RegistroID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        barraIz.setBackground(new java.awt.Color(45, 168, 1));

        javax.swing.GroupLayout barraIzLayout = new javax.swing.GroupLayout(barraIz);
        barraIz.setLayout(barraIzLayout);
        barraIzLayout.setHorizontalGroup(
            barraIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        barraIzLayout.setVerticalGroup(
            barraIzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        Registrotxt.setFont(new java.awt.Font("Comfortaa Medium", 0, 24)); // NOI18N
        Registrotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registrotxt.setText("Registro de Visitantes");

        titulo2.setFont(new java.awt.Font("Comfortaa Medium", 0, 24)); // NOI18N
        titulo2.setText("Nuevo Registro");

        nombreag.setFont(new java.awt.Font("Comfortaa Medium", 0, 14)); // NOI18N
        nombreag.setText("Nombre:");

        NombreReg.setBackground(new java.awt.Color(248, 248, 248));
        NombreReg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NombreReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreRegActionPerformed(evt);
            }
        });

        Documentotitle.setFont(new java.awt.Font("Comfortaa Medium", 0, 14)); // NOI18N
        Documentotitle.setText("Número de documento:");

        Documento.setBackground(new java.awt.Color(248, 248, 248));
        Documento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentoActionPerformed(evt);
            }
        });

        TablaRegistroVisitantes.setFont(new java.awt.Font("Comfortaa Medium", 0, 14)); // NOI18N
        TablaRegistroVisitantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TablaRegistroVisitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaRegistroVisitantesMouseClicked(evt);
            }
        });
        mostrarVisitantes.setViewportView(TablaRegistroVisitantes);

        barraDer.setBackground(new java.awt.Color(45, 168, 1));

        javax.swing.GroupLayout barraDerLayout = new javax.swing.GroupLayout(barraDer);
        barraDer.setLayout(barraDerLayout);
        barraDerLayout.setHorizontalGroup(
            barraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        barraDerLayout.setVerticalGroup(
            barraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        IDtitle.setFont(new java.awt.Font("Comfortaa Medium", 0, 14)); // NOI18N
        IDtitle.setText("ID Visitante:");

        VisitanteIDReg.setBackground(new java.awt.Color(248, 248, 248));
        VisitanteIDReg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        VisitanteIDReg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VisitanteIDReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitanteIDRegActionPerformed(evt);
            }
        });

        BotonSalida.setFont(new java.awt.Font("Comfortaa Medium", 0, 14)); // NOI18N
        BotonSalida.setLabel("Fecha y Hora de Salida");
        BotonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalidaActionPerformed(evt);
            }
        });

        BotonEntrada.setFont(new java.awt.Font("Comfortaa Medium", 0, 14)); // NOI18N
        BotonEntrada.setLabel("Fecha y Hora de Entrada");
        BotonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntradaActionPerformed(evt);
            }
        });

        IDtitle1.setFont(new java.awt.Font("Comfortaa Medium", 0, 14)); // NOI18N
        IDtitle1.setText("No. Registro");

        RegistroID.setBackground(new java.awt.Color(248, 248, 248));
        RegistroID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RegistroID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RegistroID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Documentotitle)
                            .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(BotonEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreag)
                            .addComponent(NombreReg, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VisitanteIDReg, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistroID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(barraIz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Registrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(mostrarVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(20, 20, 20)
                    .addComponent(barraDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IDtitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegistroID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(IDtitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VisitanteIDReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreag)
                        .addGap(13, 13, 13)
                        .addComponent(NombreReg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Documentotitle)
                        .addGap(8, 8, 8)
                        .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(barraIz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(Registrotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(263, 263, 263)
                            .addComponent(mostrarVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(barraDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        NombreReg.getAccessibleContext().setAccessibleParent(NombreReg);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreRegActionPerformed

    private void DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentoActionPerformed

    private void TablaRegistroVisitantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaRegistroVisitantesMouseClicked
        Visitantes objetoVisitantes = new Visitantes();
       objetoVisitantes.SeleccionarRegistro(TablaRegistroVisitantes,VisitanteIDReg,NombreReg,Documento,RegistroID);       
    }//GEN-LAST:event_TablaRegistroVisitantesMouseClicked

    private void VisitanteIDRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitanteIDRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisitanteIDRegActionPerformed

    private void BotonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalidaActionPerformed
         Visitantes objetoVisitantes = new Visitantes();
        Usuarios objetoSalidaHora = new Usuarios();
        objetoSalidaHora.InsertarSalida(RegistroID);
         objetoVisitantes.mostrarRegistros(TablaRegistroVisitantes);
    }//GEN-LAST:event_BotonSalidaActionPerformed

    private void BotonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntradaActionPerformed
          Visitantes objetoVisitantes = new Visitantes();
        Usuarios objetoEntradaHora = new Usuarios();
        objetoEntradaHora.InsertarEntrada(VisitanteIDReg);
         objetoVisitantes.mostrarRegistros(TablaRegistroVisitantes);
         
    }//GEN-LAST:event_BotonEntradaActionPerformed

    private void RegistroIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVisitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrada;
    private javax.swing.JButton BotonSalida;
    private javax.swing.JTextField Documento;
    private javax.swing.JLabel Documentotitle;
    private javax.swing.JLabel IDtitle;
    private javax.swing.JLabel IDtitle1;
    private javax.swing.JTextField NombreReg;
    private javax.swing.JTextField RegistroID;
    private javax.swing.JLabel Registrotxt;
    private javax.swing.JTable TablaRegistroVisitantes;
    private javax.swing.JTextField VisitanteIDReg;
    private javax.swing.JPanel barraDer;
    private javax.swing.JPanel barraIz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane mostrarVisitantes;
    private javax.swing.JLabel nombreag;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
