/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bienvenida = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        iniciarsesion1 = new javax.swing.JLabel();
        usuariotxt = new javax.swing.JLabel();
        contrasenatxt = new javax.swing.JLabel();
        campousuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        campocontrasena = new javax.swing.JPasswordField();
        botonIngreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondoregistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenida.setText("Bienvenidos");
        bienvenida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 220, 100));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo carvappDDDD.png"))); // NOI18N
        logo.setText("jLabel1");
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, 170));

        iniciarsesion1.setFont(new java.awt.Font("Comfortaa Medium", 0, 18)); // NOI18N
        iniciarsesion1.setText("Iniciar Sesión");
        bg.add(iniciarsesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, 30));

        usuariotxt.setFont(new java.awt.Font("Comfortaa Medium", 0, 18)); // NOI18N
        usuariotxt.setText("Usuario");
        bg.add(usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, 30));

        contrasenatxt.setFont(new java.awt.Font("Comfortaa Medium", 0, 18)); // NOI18N
        contrasenatxt.setText("Contraseña");
        bg.add(contrasenatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 120, 30));

        campousuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campousuario.setForeground(new java.awt.Color(204, 204, 204));
        campousuario.setText("Ingrese su nombre de usuario");
        campousuario.setBorder(null);
        campousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campousuarioMousePressed(evt);
            }
        });
        campousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campousuarioActionPerformed(evt);
            }
        });
        bg.add(campousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 320, 40));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 300, 20));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 300, 20));

        campocontrasena.setForeground(new java.awt.Color(204, 204, 204));
        campocontrasena.setText("********");
        campocontrasena.setBorder(null);
        campocontrasena.setCaretColor(new java.awt.Color(204, 204, 204));
        campocontrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campocontrasenaMousePressed(evt);
            }
        });
        bg.add(campocontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, 30));

        botonIngreso.setBackground(new java.awt.Color(127, 231, 82));
        botonIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonIngreso.setForeground(new java.awt.Color(102, 102, 102));
        botonIngreso.setText("INGRESAR");
        botonIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIngresoMouseClicked(evt);
            }
        });
        bg.add(botonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoucp.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        fondoregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo 1.png"))); // NOI18N
        fondoregistro.setLabelFor(fondoregistro);
        fondoregistro.setText("jLabel1");
        bg.add(fondoregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 400, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresoMouseClicked
         javax.swing.JOptionPane.showMessageDialog(this,"intento de login; \nUsuario: " + campousuario.getText()+ "\nContraseña: " + String.valueOf(campocontrasena.getPassword()),"LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE );        // TODO add your handling code here:
   
    }//GEN-LAST:event_botonIngresoMouseClicked

    private void campousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campousuarioActionPerformed

    private void campousuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campousuarioMousePressed
       if(campousuario.getText().equals("Ingrese su nombre de usuario")){
        campousuario.setText("");
        campousuario.setForeground(Color.black);
       }
        if (String.valueOf(campocontrasena.getPassword()).isEmpty()){
        campocontrasena.setText("********");
        campocontrasena.setForeground(Color.gray);
        }
    }//GEN-LAST:event_campousuarioMousePressed

    private void campocontrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campocontrasenaMousePressed
      if (String.valueOf(campocontrasena.getPassword()).equals("********")){
        campocontrasena.setText("");
        campocontrasena.setForeground(Color.black);
      }
      if(campousuario.getText().isEmpty()){
        campousuario.setText("Ingrese su nombre de usuario");
       campousuario.setForeground(Color.gray);
    }//GEN-LAST:event_campocontrasenaMousePressed

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton botonIngreso;
    private javax.swing.JPasswordField campocontrasena;
    private javax.swing.JTextField campousuario;
    private javax.swing.JLabel contrasenatxt;
    private javax.swing.JLabel fondoregistro;
    private javax.swing.JLabel iniciarsesion1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel usuariotxt;
    // End of variables declaration//GEN-END:variables
}
